FROM nginx:1.10.1

COPY default.conf /etc/nginx/conf.d/default.conf.template

ENV FPM_HOST=app FPM_PORT=9000 UPLOAD_MAX_SIZE=1m

RUN envsubst '$$FPM_HOST $$FPM_PORT $$UPLOAD_MAX_SIZE' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
