FROM nginx:1.11.1

COPY default.conf /etc/nginx/conf.d/default.conf.template

ARG FPM_HOST=app
ARG FPM_PORT=9000
ARG UPLOAD_MAX_SIZE=1m

RUN envsubst '$$FPM_HOST $$FPM_PORT $$UPLOAD_MAX_SIZE' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
